AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Swagger.

Parameters:
  Env:
    Type: String
    Default: dev
  ServiceName:
    Type: String
    Default: user-service
  APIVersion:
    Type: String
  DeployArtifactBucket:
    Type: String
    Default: cf-templates-461spye58s2i-ap-northeast-1
  AppEnvironmentLogLevel:
    Type: String
  AppEnvironmentRDSUser:
    Type: String
    Default: admin
  AppEnvironmentRDSPassword:
    Type: String
#  AppEnvironmentRDSWriterEndpoint:
#    Type: String
#  AppEnvironmentRDSReaderEndpoint:
#    Type: String

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        -
          PolicyName: "lambda_cw_policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "logs:*"
                Resource: "*"
        -
          PolicyName: "lambda_vpc_policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "ec2:CreateNetworkInterface"
                  - "ec2:DescribeNetworkInterfaces"
                  - "ec2:DetachNetworkInterface"
                  - "ec2:DeleteNetworkInterface"
                Resource: "*"

  UserLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      Handler: lambda_handler.handler
      CodeUri: lambda.zip
      Role: !GetAtt LambdaRole.Arn
      Timeout: 5
      VpcConfig:
        SecurityGroupIds:
          - !Sub "{{resolve:ssm:/ys-dev-web-${Env}/ApplicationSecurityGroup}}"
        SubnetIds:
          - Fn::ImportValue:
              !Sub ys-dev-web-application-subnet-a-${Env}
          - Fn::ImportValue:
              !Sub ys-dev-web-application-subnet-c-${Env}
      Environment:
        Variables:
          RDS_WRITER_ENDPOINT: !Sub "{{resolve:ssm:/ys-dev-web-${Env}/RDSWriterEndpoint}}"
          RDS_PROXY_WRITER_ENDPOINT: !Sub "{{resolve:ssm:/ys-dev-web-${Env}/RDSProxyWriterEndpoint}}"
          RDS_READER_ENDPOINT: !Sub "{{resolve:ssm:/ys-dev-web-${Env}/RDSReaderEndpoint}}"
          RDS_USER: !Ref AppEnvironmentRDSUser
          RDS_PASSWORD: !Ref AppEnvironmentRDSPassword

  WebApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref APIVersion
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: !Sub s3://${DeployArtifactBucket}/open-api.yml
      EndpointConfiguration:
        Type: REGIONAL
      OpenApiVersion: 3.0.1

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref UserLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

Outputs:
  UsereApiId:
    Value: !Ref WebApi
    Export:
      Name: !Sub ys-dev-web-${ServiceName}-api-id-${Env}
